services:
  # Auth Service
  auth_service:
    extends:
      file: auth_service/docker-compose.dev.yml
      service: auth_service_dev
    ports:
      - "8001:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Max size of a single log file
        max-file: "3" # Number of log files to keep

  # Super ID Service
  super_id_service:
    extends:
      file: super_id_service/docker-compose.dev.yml
      service: super_id_service_dev
    ports:
      - "8002:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Data Capture Rightmove Service
  data_capture_rightmove_service:
    extends:
      file: data_capture_rightmove_service/docker-compose.dev.yml
      service: data_capture_rightmove_service_dev
    ports:
      - "8003:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  paservices_network:
    name: paservices_network
    external: true
  supabase_network_paservices:
    external: true
    # The actual network name as created by Supabase CLI
