services:
  # Auth Service
  auth_service:
    extends:
      file: auth_service/docker-compose.dev.yml
      service: auth_service_dev
    ports:
      - "8001:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Max size of a single log file
        max-file: "3" # Number of log files to keep

  # Super ID Service
  super_id_service:
    extends:
      file: super_id_service/docker-compose.dev.yml
      service: super_id_service_dev
    ports:
      - "8002:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Data Capture Rightmove Service
  data_capture_rightmove_service:
    extends:
      file: data_capture_rightmove_service/docker-compose.dev.yml
      service: data_capture_rightmove_service_dev
    ports:
      - "8003:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Floorplan Service
  floorplan_service:
    extends:
      file: floorplan_service/docker-compose.dev.yml
      service: floorplan_service_dev
    ports:
      - "8004:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # # --- DJANGO SERVICE ---
  # sanalysis_service:
  #   container_name: sanalysis-app # Use a consistent name
  #   build:
  #     context: ./sanalysis # The path to your Django project from the root
  #     dockerfile: Dockerfile
  #   command: >
  #     sh -c "
  #       daphne analysis_service.asgi:application -b 0.0.0.0 -p 8000
  #     "
  #   volumes:
  #     - ./sanalysis:/code # Mount the Django project code
  #   ports:
  #     - "8000:8000" # Expose port 8000 to your local machine
  #   depends_on:
  #     - sanalysis_redis # Make it depend on its own Redis
  #   networks:
  #     - paservices_network
  #     - supabase_network_paservices
  #   env_file:
  #     - ./sanalysis/.env # Path to the .env file from the root

  # sanalysis_redis:
  #   container_name: sanalysis-app-redis
  #   image: redis:latest
  #   networks:
  #     - paservices_network

  # sanalysis_celery:
  #   container_name: sanalysis-app-celery
  #   build:
  #     context: ./sanalysis
  #     dockerfile: Dockerfile
  #   command: >
  #     sh -c "
  #       echo 'Waiting for sanalysis_service and redis...';
  #       while ! nc -z sanalysis_service 8000 || ! nc -z sanalysis_redis 6379; do
  #         sleep 1;
  #       done;
  #       echo 'sanalysis_service and Redis are up - starting celery worker';
  #       celery -A analysis_service worker --loglevel=info
  #     "
  #   volumes:
  #     - ./sanalysis:/code
  #   depends_on:
  #     - sanalysis_redis
  #     - sanalysis_service # The celery worker depends on the web service
  #   networks:
  #     - paservices_network
  #   env_file:
  #     - ./sanalysis/.env

  # Data Capture Service
  data_capture_service:
    extends:
      file: data_capture_service/docker-compose.dev.yml
      service: data_capture_service_dev
    ports:
      - "8006:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MCP Service
  pa_mcp:
    extends:
      file: pa_mcp/docker-compose.dev.yml
      service: pa_mcp_dev
    ports:
      - "8005:8000"
    networks:
      - paservices_network
      - supabase_network_paservices
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  paservices_network:
    name: paservices_network
    external: true
  supabase_network_paservices:
    external: true
    # The actual network name as created by Supabase CLI
# repo name = paservices
# .env encrypt with paservices
# gpg --symmetric --cipher-algo AES256 --output .env.gpg .env

# gpg --symmetric --cipher-algo AES256 \
#   --batch --yes \
#   --pinentry-mode loopback \
#   --passphrase "paservices" \
#   --output pa_mcp/.env.prod.gpg \
#   pa_mcp/.env.prod
