services:
  # Auth Service
  auth_service:
    extends:
      file: auth_service/docker-compose.dev.yml
      service: auth_service_dev
    ports:
      - "8001:8000"

  # Super ID Service
  super_id_service:
    extends:
      file: super_id_service/docker-compose.dev.yml
      service: super_id_service_dev
    ports:
      - "8002:8000"

  # Data Capture Rightmove Service
  data_capture_rightmove_service:
    extends:
      file: data_capture_rightmove_service/docker-compose.dev.yml
      service: data_capture_rightmove_service_dev
    ports:
      - "8003:8000"

networks:
  paservices_network:
    name: paservices_network
    driver: bridge
  supabase_network_paservices:
    external: true
    # The actual network name as created by Supabase CLI
