"""convert rooms column to jsonb

Revision ID: 299bfdacb52a
Revises: 7c996d78f3f5
Create Date: 2025-11-05 18:12:45.800885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '299bfdacb52a'
down_revision = '7c996d78f3f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'api_property_details',
        'rooms',
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        schema='rightmove',
        postgresql_using='to_jsonb(rooms)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'api_property_details',
        'rooms',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
        schema='rightmove',
        postgresql_using="""
            CASE
                WHEN rooms IS NULL THEN NULL
                ELSE (
                    SELECT array_agg(elem)
                    FROM jsonb_array_elements_text(rooms) AS elem
                )
            END
        """,
    )
    # ### end Alembic commands ###
