"""add workflow status table

Revision ID: 721604977ae4
Revises: 299bfdacb52a
Create Date: 2025-11-07 06:58:56.051945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '721604977ae4'
down_revision = '299bfdacb52a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=255), nullable=True),
    sa.Column('context', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('data_location', sa.String(length=2048), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_status')),
    sa.UniqueConstraint('super_id', 'context', name='uq_workflow_status_context'),
    schema='rightmove'
    )
    op.create_index(op.f('ix_rightmove_workflow_status_property_id'), 'workflow_status', ['property_id'], unique=False, schema='rightmove')
    op.create_index(op.f('ix_rightmove_workflow_status_super_id'), 'workflow_status', ['super_id'], unique=False, schema='rightmove')
    op.alter_column('property_display_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.alter_column('property_display_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.create_index(op.f('ix_rightmove_property_display_prices_super_id'), 'property_display_prices', ['super_id'], unique=False, schema='rightmove')
    op.drop_constraint(op.f('property_display_prices_property_listing_snapshot_id_fkey'), 'property_display_prices', schema='rightmove', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_display_prices_property_listing_snapshot_id_property_listings'), 'property_display_prices', 'property_listings', ['property_listing_snapshot_id'], ['snapshot_id'], source_schema='rightmove', referent_schema='rightmove')
    op.alter_column('property_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.alter_column('property_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.create_index(op.f('ix_rightmove_property_images_super_id'), 'property_images', ['super_id'], unique=False, schema='rightmove')
    op.drop_constraint(op.f('property_images_property_listing_snapshot_id_fkey'), 'property_images', schema='rightmove', type_='foreignkey')
    op.create_foreign_key(op.f('fk_property_images_property_listing_snapshot_id_property_listings'), 'property_images', 'property_listings', ['property_listing_snapshot_id'], ['snapshot_id'], source_schema='rightmove', referent_schema='rightmove')
    op.alter_column('property_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.alter_column('property_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.create_index(op.f('ix_rightmove_property_listings_id'), 'property_listings', ['id'], unique=False, schema='rightmove')
    op.create_index(op.f('ix_rightmove_property_listings_super_id'), 'property_listings', ['super_id'], unique=False, schema='rightmove')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rightmove_property_listings_super_id'), table_name='property_listings', schema='rightmove')
    op.drop_index(op.f('ix_rightmove_property_listings_id'), table_name='property_listings', schema='rightmove')
    op.alter_column('property_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.alter_column('property_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.drop_constraint(op.f('fk_property_images_property_listing_snapshot_id_property_listings'), 'property_images', schema='rightmove', type_='foreignkey')
    op.create_foreign_key(op.f('property_images_property_listing_snapshot_id_fkey'), 'property_images', 'property_listings', ['property_listing_snapshot_id'], ['snapshot_id'], source_schema='rightmove', referent_schema='rightmove', ondelete='CASCADE')
    op.drop_index(op.f('ix_rightmove_property_images_super_id'), table_name='property_images', schema='rightmove')
    op.alter_column('property_images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.alter_column('property_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.drop_constraint(op.f('fk_property_display_prices_property_listing_snapshot_id_property_listings'), 'property_display_prices', schema='rightmove', type_='foreignkey')
    op.create_foreign_key(op.f('property_display_prices_property_listing_snapshot_id_fkey'), 'property_display_prices', 'property_listings', ['property_listing_snapshot_id'], ['snapshot_id'], source_schema='rightmove', referent_schema='rightmove', ondelete='CASCADE')
    op.drop_index(op.f('ix_rightmove_property_display_prices_super_id'), table_name='property_display_prices', schema='rightmove')
    op.alter_column('property_display_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.alter_column('property_display_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='rightmove')
    op.drop_index(op.f('ix_rightmove_workflow_status_super_id'), table_name='workflow_status', schema='rightmove')
    op.drop_index(op.f('ix_rightmove_workflow_status_property_id'), table_name='workflow_status', schema='rightmove')
    op.drop_table('workflow_status', schema='rightmove')
    # ### end Alembic commands ###
