"""add property listings models

Revision ID: 7c996d78f3f5
Revises: bad9982f7e68
Create Date: 2025-07-11 14:54:20.575032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c996d78f3f5'
down_revision = 'bad9982f7e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_listings',
    sa.Column('snapshot_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_source_endpoint', sa.String(length=100), nullable=False),
    sa.Column('added_or_reduced', sa.String(length=255), nullable=True),
    sa.Column('auction', sa.Boolean(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('commercial', sa.Boolean(), nullable=True),
    sa.Column('contact_url', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('development', sa.Boolean(), nullable=True),
    sa.Column('display_address', sa.String(length=512), nullable=True),
    sa.Column('display_size', sa.String(length=100), nullable=True),
    sa.Column('display_status', sa.String(length=255), nullable=True),
    sa.Column('distance', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('enhanced_listing', sa.Boolean(), nullable=True),
    sa.Column('enquired_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('featured_property', sa.Boolean(), nullable=True),
    sa.Column('fees_apply', sa.Boolean(), nullable=True),
    sa.Column('fees_apply_text', sa.Text(), nullable=True),
    sa.Column('first_visible_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('formatted_branch_name', sa.String(length=255), nullable=True),
    sa.Column('formatted_distance', sa.String(length=100), nullable=True),
    sa.Column('has_brand_plus', sa.Boolean(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('is_recent', sa.Boolean(), nullable=True),
    sa.Column('keyword_match_type', sa.String(length=100), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('number_of_floorplans', sa.Integer(), nullable=True),
    sa.Column('number_of_images', sa.Integer(), nullable=True),
    sa.Column('number_of_virtual_tours', sa.Integer(), nullable=True),
    sa.Column('online_viewings_available', sa.Boolean(), nullable=True),
    sa.Column('premium_listing', sa.Boolean(), nullable=True),
    sa.Column('property_sub_type', sa.String(length=100), nullable=True),
    sa.Column('property_type_full_description', sa.String(length=255), nullable=True),
    sa.Column('property_url', sa.Text(), nullable=True),
    sa.Column('residential', sa.Boolean(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('show_on_map', sa.Boolean(), nullable=True),
    sa.Column('static_map_url', sa.Text(), nullable=True),
    sa.Column('students', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('customer_branch_display_name', sa.String(length=255), nullable=True),
    sa.Column('customer_branch_id', sa.Integer(), nullable=True),
    sa.Column('customer_branch_landing_page_url', sa.Text(), nullable=True),
    sa.Column('customer_branch_name', sa.String(length=255), nullable=True),
    sa.Column('customer_brand_plus_logo_uri', sa.Text(), nullable=True),
    sa.Column('customer_brand_plus_logo_url', sa.Text(), nullable=True),
    sa.Column('customer_brand_trading_name', sa.String(length=255), nullable=True),
    sa.Column('customer_build_to_rent', sa.Boolean(), nullable=True),
    sa.Column('customer_build_to_rent_benefits_json', sa.JSON(), nullable=True),
    sa.Column('customer_commercial', sa.Boolean(), nullable=True),
    sa.Column('customer_contact_telephone', sa.String(length=50), nullable=True),
    sa.Column('customer_development', sa.Boolean(), nullable=True),
    sa.Column('customer_development_content', sa.Text(), nullable=True),
    sa.Column('customer_enhanced_listing', sa.Boolean(), nullable=True),
    sa.Column('customer_show_on_map', sa.Boolean(), nullable=True),
    sa.Column('customer_show_reduced_properties', sa.Boolean(), nullable=True),
    sa.Column('listing_update_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('listing_update_reason', sa.String(length=100), nullable=True),
    sa.Column('location_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('location_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('lozenge_model_matching_lozenges_json', sa.JSON(), nullable=True),
    sa.Column('price_amount', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('price_currency_code', sa.String(length=10), nullable=True),
    sa.Column('price_frequency', sa.String(length=50), nullable=True),
    sa.Column('product_label_text', sa.String(length=255), nullable=True),
    sa.Column('product_label_spotlight_label', sa.Boolean(), nullable=True),
    sa.Column('property_images_main_image_src', sa.Text(), nullable=True),
    sa.Column('property_images_main_map_image_src', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_property_listings')),
    schema='rightmove'
    )
    op.create_index(op.f('ix_rightmove_property_listings_id'), 'property_listings', ['id'], unique=False, schema='rightmove')
    op.create_index(op.f('ix_rightmove_property_listings_super_id'), 'property_listings', ['super_id'], unique=False, schema='rightmove')
    op.create_table('property_display_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_listing_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('display_price', sa.String(length=100), nullable=True),
    sa.Column('display_price_qualifier', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['property_listing_snapshot_id'], ['rightmove.property_listings.snapshot_id'], name=op.f('fk_property_display_prices_property_listing_snapshot_id_property_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_display_prices')),
    schema='rightmove'
    )
    op.create_index(op.f('ix_rightmove_property_display_prices_super_id'), 'property_display_prices', ['super_id'], unique=False, schema='rightmove')
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_listing_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('src_url', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['property_listing_snapshot_id'], ['rightmove.property_listings.snapshot_id'], name=op.f('fk_property_images_property_listing_snapshot_id_property_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_images')),
    schema='rightmove'
    )
    op.create_index(op.f('ix_rightmove_property_images_super_id'), 'property_images', ['super_id'], unique=False, schema='rightmove')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rightmove_property_images_super_id'), table_name='property_images', schema='rightmove')
    op.drop_table('property_images', schema='rightmove')
    op.drop_index(op.f('ix_rightmove_property_display_prices_super_id'), table_name='property_display_prices', schema='rightmove')
    op.drop_table('property_display_prices', schema='rightmove')
    op.drop_index(op.f('ix_rightmove_property_listings_super_id'), table_name='property_listings', schema='rightmove')
    op.drop_index(op.f('ix_rightmove_property_listings_id'), table_name='property_listings', schema='rightmove')
    op.drop_table('property_listings', schema='rightmove')
    # ### end Alembic commands ###
