# auth_service/docker-compose.test.yml
services:
  auth_service_test:
    build:
      context: .
      dockerfile: Dockerfile.dev # Can reuse dev Dockerfile for testing
    environment:
      - ENVIRONMENT=testing
      # Override database URL for an isolated test database
      - AUTH_SERVICE_DATABASE_URL=postgresql+asyncpg://postgres:postgres@supabase_db_paservices:54322/auth_test_db
    env_file:
      - ./.env.test
    networks:
      - paservices_network
      - supabase_network_paservices
    command: ["pytest", "-v", "tests/"]

networks:
  paservices_network:
    name: paservices_network
    driver: bridge
  supabase_network_paservices:
    external: true
