name: Reusable Build and Push

description: Builds and pushes a Docker image for a service

inputs:
  service_name:
    description: 'Name of the service to build'
    required: true
    type: string
  image_name:
    description: 'Full Docker image name (including registry)'
    required: true
    type: string
  dockerhub_username:
    description: 'Docker Hub username'
    required: true
    type: string
  dockerhub_token:
    description: 'Docker Hub access token'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up QEMU for multi-architecture builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Build and Push Docker Image for ${{ inputs.service_name }}
      uses: docker/build-push-action@v5
      with:
        context: ./${{ inputs.service_name }}
        file: ./${{ inputs.service_name }}/Dockerfile.prod
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ inputs.image_name }}:${{ github.sha }}
          ${{ inputs.image_name }}:latest
