"""Initial schema

Revision ID: 2e2200ed902f
Revises: 
Create Date: 2025-08-20 22:29:13.323546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e2200ed902f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floorplan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floorplan_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.Enum('REQUEST_RECEIVED', 'ANALYZER_CALL_ATTEMPT', 'ANALYZER_CALL_SUCCESS', 'ANALYZER_CALL_FAILURE', 'WEBHOOK_RECEIVED', 'DATA_STORAGE_SUCCESS', 'DATA_STORAGE_FAILURE', name='floorplaneventtypeenum'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floorplan_events')),
    schema='floorplan'
    )
    op.create_index(op.f('ix_floorplan_floorplan_events_event_type'), 'floorplan_events', ['event_type'], unique=False, schema='floorplan')
    op.create_index(op.f('ix_floorplan_floorplan_events_floorplan_id'), 'floorplan_events', ['floorplan_id'], unique=False, schema='floorplan')
    op.create_index(op.f('ix_floorplan_floorplan_events_super_id'), 'floorplan_events', ['super_id'], unique=False, schema='floorplan')
    op.create_table('fp_property_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('property_id', sa.String(length=255), nullable=True),
    sa.Column('floorplan_id', sa.String(length=64), nullable=True),
    sa.Column('original_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fp_property_data')),
    schema='floorplan'
    )
    op.create_index(op.f('ix_floorplan_fp_property_data_floorplan_id'), 'fp_property_data', ['floorplan_id'], unique=False, schema='floorplan')
    op.create_index(op.f('ix_floorplan_fp_property_data_property_id'), 'fp_property_data', ['property_id'], unique=False, schema='floorplan')
    op.create_index(op.f('ix_floorplan_fp_property_data_super_id'), 'fp_property_data', ['super_id'], unique=False, schema='floorplan')
    op.create_table('fp_analysis_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fp_property_data_id', sa.Integer(), nullable=False),
    sa.Column('json_file_url', sa.String(length=1024), nullable=True),
    sa.Column('csv_url', sa.String(length=1024), nullable=True),
    sa.Column('total_area_csv_url', sa.String(length=1024), nullable=True),
    sa.Column('image_labelme_side_by_side_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fp_property_data_id'], ['floorplan.fp_property_data.id'], name=op.f('fk_fp_analysis_urls_fp_property_data_id_fp_property_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fp_analysis_urls')),
    schema='floorplan'
    )
    op.create_index(op.f('ix_floorplan_fp_analysis_urls_super_id'), 'fp_analysis_urls', ['super_id'], unique=False, schema='floorplan')
    op.create_table('fp_room_csv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fp_analysis_urls_id', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(length=100), nullable=True),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('is_segment', sa.String(length=50), nullable=True),
    sa.Column('dimensions_imperial', sa.String(length=100), nullable=True),
    sa.Column('dimensions_metric', sa.String(length=100), nullable=True),
    sa.Column('room_id', sa.Float(), nullable=True),
    sa.Column('no_of_door', sa.Float(), nullable=True),
    sa.Column('no_of_window', sa.Float(), nullable=True),
    sa.Column('no_of_room_points', sa.Float(), nullable=True),
    sa.Column('min_x_pixels_csv', sa.Float(), nullable=True),
    sa.Column('min_y_pixels_csv', sa.Float(), nullable=True),
    sa.Column('max_x_pixels_csv', sa.Float(), nullable=True),
    sa.Column('max_y_pixels_csv', sa.Float(), nullable=True),
    sa.Column('max_area_metric_csv', sa.Float(), nullable=True),
    sa.Column('max_area_imperial_csv', sa.Float(), nullable=True),
    sa.Column('max_area_pixels_csv', sa.Float(), nullable=True),
    sa.Column('actual_area_pixels_csv', sa.Float(), nullable=True),
    sa.Column('pixel_ratio_csv', sa.Float(), nullable=True),
    sa.Column('scale_metric_csv', sa.Float(), nullable=True),
    sa.Column('scale_imperial_csv', sa.Float(), nullable=True),
    sa.Column('calculated_sq_area_metric_csv', sa.Float(), nullable=True),
    sa.Column('calc_floor_total_metric_csv', sa.Float(), nullable=True),
    sa.Column('calculated_area_imperial_csv', sa.Float(), nullable=True),
    sa.Column('calc_floor_total_imperial_csv', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fp_analysis_urls_id'], ['floorplan.fp_analysis_urls.id'], name=op.f('fk_fp_room_csv_data_fp_analysis_urls_id_fp_analysis_urls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fp_room_csv_data')),
    schema='floorplan'
    )
    op.create_index(op.f('ix_floorplan_fp_room_csv_data_floor_name'), 'fp_room_csv_data', ['floor_name'], unique=False, schema='floorplan')
    op.create_index(op.f('ix_floorplan_fp_room_csv_data_room_id'), 'fp_room_csv_data', ['room_id'], unique=False, schema='floorplan')
    op.create_index(op.f('ix_floorplan_fp_room_csv_data_super_id'), 'fp_room_csv_data', ['super_id'], unique=False, schema='floorplan')
    op.create_table('fp_total_areas_csv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fp_analysis_urls_id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=500), nullable=True),
    sa.Column('square_meters', sa.Float(), nullable=True),
    sa.Column('square_feet', sa.Float(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('total_named_rooms', sa.Integer(), nullable=True),
    sa.Column('total_segments', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('total_objects', sa.Integer(), nullable=True),
    sa.Column('total_door_objects', sa.Integer(), nullable=True),
    sa.Column('total_window_objects', sa.Integer(), nullable=True),
    sa.Column('total_stair_objects', sa.Integer(), nullable=True),
    sa.Column('list_of_objects', sa.Text(), nullable=True),
    sa.Column('total_actual_pixels', sa.Float(), nullable=True),
    sa.Column('metric_scale', sa.Float(), nullable=True),
    sa.Column('imperial_scale', sa.Float(), nullable=True),
    sa.Column('input_image_tokens', sa.Integer(), nullable=True),
    sa.Column('input_text_tokens', sa.Integer(), nullable=True),
    sa.Column('output_text_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fp_analysis_urls_id'], ['floorplan.fp_analysis_urls.id'], name=op.f('fk_fp_total_areas_csv_data_fp_analysis_urls_id_fp_analysis_urls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fp_total_areas_csv_data')),
    schema='floorplan'
    )
    op.create_index(op.f('ix_floorplan_fp_total_areas_csv_data_super_id'), 'fp_total_areas_csv_data', ['super_id'], unique=False, schema='floorplan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_floorplan_fp_total_areas_csv_data_super_id'), table_name='fp_total_areas_csv_data', schema='floorplan')
    op.drop_table('fp_total_areas_csv_data', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_room_csv_data_super_id'), table_name='fp_room_csv_data', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_room_csv_data_room_id'), table_name='fp_room_csv_data', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_room_csv_data_floor_name'), table_name='fp_room_csv_data', schema='floorplan')
    op.drop_table('fp_room_csv_data', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_analysis_urls_super_id'), table_name='fp_analysis_urls', schema='floorplan')
    op.drop_table('fp_analysis_urls', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_property_data_super_id'), table_name='fp_property_data', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_property_data_property_id'), table_name='fp_property_data', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_property_data_floorplan_id'), table_name='fp_property_data', schema='floorplan')
    op.drop_table('fp_property_data', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_floorplan_events_super_id'), table_name='floorplan_events', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_floorplan_events_floorplan_id'), table_name='floorplan_events', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_floorplan_events_event_type'), table_name='floorplan_events', schema='floorplan')
    op.drop_table('floorplan_events', schema='floorplan')
    # ### end Alembic commands ###
