"""add workflow status table

Revision ID: 65bab104331b
Revises: d0e166bb1756
Create Date: 2025-11-07 06:05:01.101802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bab104331b'
down_revision = 'd0e166bb1756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_workflow_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=255), nullable=True),
    sa.Column('context', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('data_location', sa.String(length=2048), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('super_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fp_workflow_status')),
    sa.UniqueConstraint('super_id', 'context', name='uq_fp_workflow_status_context'),
    schema='floorplan'
    )
    op.create_index(op.f('ix_floorplan_fp_workflow_status_property_id'), 'fp_workflow_status', ['property_id'], unique=False, schema='floorplan')
    op.create_index(op.f('ix_floorplan_fp_workflow_status_super_id'), 'fp_workflow_status', ['super_id'], unique=False, schema='floorplan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_floorplan_fp_workflow_status_super_id'), table_name='fp_workflow_status', schema='floorplan')
    op.drop_index(op.f('ix_floorplan_fp_workflow_status_property_id'), table_name='fp_workflow_status', schema='floorplan')
    op.drop_table('fp_workflow_status', schema='floorplan')
    # ### end Alembic commands ###
