"""add callback_urls to fp_property_data

Revision ID: 9c37b1156ddf
Revises: 65bab104331b
Create Date: 2025-12-18 19:08:58.466059

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9c37b1156ddf"
down_revision = "65bab104331b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fp_property_data",
        sa.Column(
            "callback_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        schema="floorplan",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fp_property_data", "callback_urls", schema="floorplan")
    # ### end Alembic commands ###
