"""add analysis_updates

Revision ID: 04a0558eb695
Revises: 1428835c1bcd
Create Date: 2025-12-19 15:22:33.116647

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04a0558eb695"
down_revision: Union[str, None] = "1428835c1bcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_updates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("super_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("context", sa.String(), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_location", sa.String(), nullable=True),
        sa.Column(
            "final_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_updates_received_at"),
        "analysis_updates",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_updates_super_id"),
        "analysis_updates",
        ["super_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_updates_super_id"), table_name="analysis_updates")
    op.drop_index(
        op.f("ix_analysis_updates_received_at"), table_name="analysis_updates"
    )
    op.drop_table("analysis_updates")
    # ### end Alembic commands ###
