"""init

Revision ID: 1428835c1bcd
Revises:
Create Date: 2025-12-02 15:00:04.346692

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1428835c1bcd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_results",
        sa.Column("super_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("remote_status", sa.String(), nullable=True),
        sa.Column("property_url", sa.String(), nullable=True),
        sa.Column("workflow_callback_url", sa.String(), nullable=True),
        sa.Column("n8n_triggered", sa.Boolean(), nullable=True),
        sa.Column(
            "final_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("super_id"),
    )
    op.create_index(
        op.f("ix_analysis_results_super_id"),
        "analysis_results",
        ["super_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_results_super_id"), table_name="analysis_results")
    op.drop_table("analysis_results")
    # ### end Alembic commands ###
