"""initial schema

Revision ID: ac12c7784304
Revises:
Create Date: 2026-03-13 10:39:52.976663

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ac12c7784304"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_capture_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("target_domain", sa.String(length=512), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "ORCHESTRATED",
                "DIRECT_ADAPTER",
                name="data_capture_run_mode",
                schema="data_capture",
            ),
            nullable=False,
        ),
        sa.Column("selected_adapter", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "BASELINE_RUNNING",
                "SCRAPING",
                "VALIDATING",
                "COMPLETED",
                "FAILED",
                "COMPLETED_WITH_WARNINGS",
                name="data_capture_run_status",
                schema="data_capture",
            ),
            nullable=False,
        ),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("fallback_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "route_decision_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("super_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_capture_runs")),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_runs_status"),
        "data_capture_runs",
        ["status"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_runs_super_id"),
        "data_capture_runs",
        ["super_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_runs_target_domain"),
        "data_capture_runs",
        ["target_domain"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_runs_target_url"),
        "data_capture_runs",
        ["target_url"],
        unique=False,
        schema="data_capture",
    )
    op.create_table(
        "provider_data_captures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("provider_type", sa.String(length=128), nullable=False),
        sa.Column(
            "supported_domains", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_data_captures")),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_provider_data_captures_name"),
        "provider_data_captures",
        ["name"],
        unique=True,
        schema="data_capture",
    )
    op.create_table(
        "canonical_property_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column(
            "snapshot_id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("source_adapter", sa.String(length=128), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("address_road", sa.String(length=512), nullable=True),
        sa.Column("price", sa.String(length=128), nullable=True),
        sa.Column("price_text", sa.String(length=256), nullable=True),
        sa.Column("address_town", sa.String(length=256), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("estate_agent_name", sa.String(length=512), nullable=True),
        sa.Column("agent_address", sa.Text(), nullable=True),
        sa.Column("transaction_type", sa.String(length=64), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("property_type", sa.String(length=128), nullable=True),
        sa.Column("full_address", sa.Text(), nullable=True),
        sa.Column("postcode", sa.String(length=16), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rightmove_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "extras_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("super_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["data_capture.data_capture_runs.id"],
            name=op.f("fk_canonical_property_snapshots_run_id_data_capture_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_property_snapshots")),
        sa.UniqueConstraint(
            "snapshot_id", name=op.f("uq_canonical_property_snapshots_snapshot_id")
        ),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_canonical_property_snapshots_run_id"),
        "canonical_property_snapshots",
        ["run_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_canonical_property_snapshots_super_id"),
        "canonical_property_snapshots",
        ["super_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_table(
        "data_capture_run_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("adapter_name", sa.String(length=128), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "BASELINE",
                "DATA_CAPTURE",
                "VALIDATION",
                name="step_type",
                schema="data_capture",
            ),
            nullable=False,
        ),
        sa.Column("provider_type", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                name="step_status",
                schema="data_capture",
            ),
            nullable=False,
        ),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("provider_run_id", sa.String(length=512), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("super_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["data_capture.data_capture_runs.id"],
            name=op.f("fk_data_capture_run_steps_run_id_data_capture_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_capture_run_steps")),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_run_steps_run_id"),
        "data_capture_run_steps",
        ["run_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_run_steps_super_id"),
        "data_capture_run_steps",
        ["super_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_table(
        "canonical_media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("media_type", sa.String(length=32), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_high_res", sa.Boolean(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("super_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_capture.canonical_property_snapshots.id"],
            name=op.f("fk_canonical_media_snapshot_id_canonical_property_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_media")),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_canonical_media_snapshot_id"),
        "canonical_media",
        ["snapshot_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_canonical_media_super_id"),
        "canonical_media",
        ["super_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_table(
        "data_capture_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("adapter_name", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=256), nullable=False),
        sa.Column("credits_used", sa.Float(), nullable=True),
        sa.Column("request_count", sa.Integer(), nullable=True),
        sa.Column("response_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("super_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["data_capture.data_capture_runs.id"],
            name=op.f("fk_data_capture_usage_run_id_data_capture_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["data_capture.data_capture_run_steps.id"],
            name=op.f("fk_data_capture_usage_step_id_data_capture_run_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_capture_usage")),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_usage_run_id"),
        "data_capture_usage",
        ["run_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_usage_step_id"),
        "data_capture_usage",
        ["step_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_data_capture_usage_super_id"),
        "data_capture_usage",
        ["super_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_table(
        "source_raw_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("adapter_name", sa.String(length=128), nullable=False),
        sa.Column("source_domain", sa.String(length=512), nullable=True),
        sa.Column(
            "payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column(
            "http_meta_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("super_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["data_capture.data_capture_runs.id"],
            name=op.f("fk_source_raw_records_run_id_data_capture_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["data_capture.data_capture_run_steps.id"],
            name=op.f("fk_source_raw_records_step_id_data_capture_run_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_raw_records")),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_source_raw_records_run_id"),
        "source_raw_records",
        ["run_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_source_raw_records_step_id"),
        "source_raw_records",
        ["step_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_source_raw_records_super_id"),
        "source_raw_records",
        ["super_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_table(
        "source_parsed_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=False),
        sa.Column("raw_record_id", sa.UUID(), nullable=False),
        sa.Column("adapter_name", sa.String(length=128), nullable=False),
        sa.Column(
            "parsed_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "missing_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "field_presence_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("super_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["data_capture.source_raw_records.id"],
            name=op.f("fk_source_parsed_records_raw_record_id_source_raw_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["data_capture.data_capture_runs.id"],
            name=op.f("fk_source_parsed_records_run_id_data_capture_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["data_capture.data_capture_run_steps.id"],
            name=op.f("fk_source_parsed_records_step_id_data_capture_run_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_parsed_records")),
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_source_parsed_records_run_id"),
        "source_parsed_records",
        ["run_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_source_parsed_records_step_id"),
        "source_parsed_records",
        ["step_id"],
        unique=False,
        schema="data_capture",
    )
    op.create_index(
        op.f("ix_data_capture_source_parsed_records_super_id"),
        "source_parsed_records",
        ["super_id"],
        unique=False,
        schema="data_capture",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_capture_source_parsed_records_super_id"),
        table_name="source_parsed_records",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_source_parsed_records_step_id"),
        table_name="source_parsed_records",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_source_parsed_records_run_id"),
        table_name="source_parsed_records",
        schema="data_capture",
    )
    op.drop_table("source_parsed_records", schema="data_capture")
    op.drop_index(
        op.f("ix_data_capture_source_raw_records_super_id"),
        table_name="source_raw_records",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_source_raw_records_step_id"),
        table_name="source_raw_records",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_source_raw_records_run_id"),
        table_name="source_raw_records",
        schema="data_capture",
    )
    op.drop_table("source_raw_records", schema="data_capture")
    op.drop_index(
        op.f("ix_data_capture_data_capture_usage_super_id"),
        table_name="data_capture_usage",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_data_capture_usage_step_id"),
        table_name="data_capture_usage",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_data_capture_usage_run_id"),
        table_name="data_capture_usage",
        schema="data_capture",
    )
    op.drop_table("data_capture_usage", schema="data_capture")
    op.drop_index(
        op.f("ix_data_capture_canonical_media_super_id"),
        table_name="canonical_media",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_canonical_media_snapshot_id"),
        table_name="canonical_media",
        schema="data_capture",
    )
    op.drop_table("canonical_media", schema="data_capture")
    op.drop_index(
        op.f("ix_data_capture_data_capture_run_steps_super_id"),
        table_name="data_capture_run_steps",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_data_capture_run_steps_run_id"),
        table_name="data_capture_run_steps",
        schema="data_capture",
    )
    op.drop_table("data_capture_run_steps", schema="data_capture")
    op.drop_index(
        op.f("ix_data_capture_canonical_property_snapshots_super_id"),
        table_name="canonical_property_snapshots",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_canonical_property_snapshots_run_id"),
        table_name="canonical_property_snapshots",
        schema="data_capture",
    )
    op.drop_table("canonical_property_snapshots", schema="data_capture")
    op.drop_index(
        op.f("ix_data_capture_provider_data_captures_name"),
        table_name="provider_data_captures",
        schema="data_capture",
    )
    op.drop_table("provider_data_captures", schema="data_capture")
    op.drop_index(
        op.f("ix_data_capture_data_capture_runs_target_url"),
        table_name="data_capture_runs",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_data_capture_runs_target_domain"),
        table_name="data_capture_runs",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_data_capture_runs_super_id"),
        table_name="data_capture_runs",
        schema="data_capture",
    )
    op.drop_index(
        op.f("ix_data_capture_data_capture_runs_status"),
        table_name="data_capture_runs",
        schema="data_capture",
    )
    op.drop_table("data_capture_runs", schema="data_capture")
    # ### end Alembic commands ###
