apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-capture-rightmove-service
  labels:
    app: data-capture-rightmove-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-capture-rightmove-service
  template:
    metadata:
      labels:
        app: data-capture-rightmove-service
    spec:
      containers:
        - name: data-capture-rightmove-service
          image: ${DOCKER_IMAGE_TAG}
          ports:
            - containerPort: 8000
          env:
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_ENVIRONMENT
              value: "production"
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_ROOT_PATH
              value: "/api/v1"
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_LOGGING_LEVEL
              value: "INFO"
            # Values from ConfigMap
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: data-capture-rightmove-config
                  key: AUTH_SERVICE_URL
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPER_ID_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: data-capture-rightmove-config
                  key: SUPER_ID_SERVICE_URL
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_RATE_LIMIT_REQUESTS_PER_MINUTE
              valueFrom:
                configMapKeyRef:
                  name: data-capture-rightmove-config
                  key: RATE_LIMIT_REQUESTS_PER_MINUTE
            # Values from Secrets
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATABASE_URL
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: SUPABASE_URL
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: SUPABASE_ANON_KEY
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: SUPABASE_SERVICE_ROLE_KEY
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_M2M_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: M2M_CLIENT_ID
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_M2M_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: M2M_CLIENT_SECRET
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: JWT_SECRET_KEY
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: REDIS_URL
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_RAPID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: RAPIDAPI_KEY
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 20
