# k8s/data-capture-rightmove-service/migration-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: data-capture-rightmove-migration
  labels:
    app: data-capture-rightmove-service
    component: migration
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: data-capture-rightmove-migration
          image: ${DOCKER_IMAGE_TAG}
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATA_CAPTURE_RIGHTMOVE_SERVICE_DATABASE_URL
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_URL
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_ANON_KEY
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATA_CAPTURE_RIGHTMOVE_SERVICE_SUPABASE_SERVICE_ROLE_KEY
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_M2M_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATA_CAPTURE_RIGHTMOVE_SERVICE_M2M_CLIENT_ID
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_M2M_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATA_CAPTURE_RIGHTMOVE_SERVICE_M2M_CLIENT_SECRET
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_RAPID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATA_CAPTURE_RIGHTMOVE_SERVICE_RAPID_API_KEY
            # Add any other env vars required by your migration script/Alembic env.py
            - name: ENVIRONMENT
              value: "production"
