# k8s/data-capture-rightmove-service/migration-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: data-capture-rightmove-migration
  labels:
    app: data-capture-rightmove-service
    component: migration
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: data-capture-rightmove-migration
          image: ${DOCKER_IMAGE_TAG}
          # command: ["alembic", "upgrade", "head"]
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "--- DEBUGGING: Pod is sleeping for 10 minutes. ---"
              sleep 600
          env:
            - name: DATA_CAPTURE_RIGHTMOVE_SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: data-capture-rightmove-secrets
                  key: DATABASE_URL
            # Add any other env vars required by your migration script/Alembic env.py
            - name: ENVIRONMENT
              value: "production"
